name: Releases cross platform binaries for nodejs-snowflake

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [12.17.0, 14.16.0]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci

      - name: Build NodeJS Snowflake
        run: npm run build

      - name: Run Tests
        run: npm t

      - name: Publish artifacts on Github
        run: |
          npm i -g prebuild
          prebuild --all -r napi -u ${{ secrets.GITHUB_TOKEN }} --strip
          
      - name: Publish Package to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

