name: Publishes to package to NPM

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.0
      - name: Install Dependencies
        run: npm ci

      - name: Build NodeJS Snowflake
        run: npm run build

      - name: Run Tests
        run: npm t
          
      - name: Publish Package to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

