name: Runs tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
      - name: Setup Wasm Pack
        uses: jetli/wasm-pack-action@v0.3.0
      - name: Run Tests
        run: wasm-pack test --node
